MOUSE_ENTER run "/bin/bash" "-c" "${ORB_DIR:-$HOME/.config/orb}/orb_hover.sh"
MOUSE_LEAVE run "/bin/bash" "-c" "${ORB_DIR:-$HOME/.config/orb}/orb_leave.sh"
MBTN_LEFT run "/bin/bash" "-c" "${ORB_DIR:-$HOME/.config/orb}/orb_action.sh"
